export const SET_PEOPLE = 'SET_PEOPLE';
export const SET_LOADING_PEOPLE = 'SET_LOADING_PEOPLE';
export const CLEAR_LOADING_PEOPLE = 'CLEAR_LOADING_PEOPLE';
export const SET_FILM = 'SET_FILM';
export const SET_LOADING_FILM = 'SET_LOADING_FILM';
export const CLEAR_LOADING_FILM = 'CLEAR_LOADING_FILM';
